# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       mer-graphics-adaptation

# >> macros
# << macros
%define adaptation_name sample
%define debug_package %{nil}

Summary:    Graphics adaptation for %{adaptation_name}
Version:    0.1.x
Release:    1
Group:      Graphics/Display and Graphics Adaptation
License:    XYZ Proprietary
Source0:    binary-blobs-0.1.0.tar.bz2
Source100:  mer-graphics-adaptation.yaml

%description
%{summary}.


%package devel
Summary:    Development files for %{adaptation_name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
%{summary}


%package libEGL
Summary:    EGL for %{adaptation_name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libEGL
Provides:   libEGL.so.1

%description libEGL
%{summary}


%package libEGL-devel
Summary:    EGL development headers for %{adaptation_name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   %{name}-libEGL = %{version}-%{release}
Requires:   %{name}-devel = %{version}-%{release}
Provides:   libEGL-devel

%description libEGL-devel
%{summary}


%package libGLESv1
Summary:    GLESv1 for %{adaptation_name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libGLESv1
Provides:   libGLES_CM.so.1

%description libGLESv1
%{summary}


%package libGLESv1-devel
Summary:    GLESv1 development headers for %{adaptation_name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   %{name}-libGLESv1 = %{version}-%{release}
Requires:   %{name}-devel = %{version}-%{release}
Provides:   libGLESv1-devel

%description libGLESv1-devel
%{summary}


%package libGLESv2
Summary:    GLESv2 for %{adaptation_name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libGLESv2
Provides:   libGLESv2.so.2

%description libGLESv2
%{summary}


%package libGLESv2-devel
Summary:    GLESv2 development headers for %{adaptation_name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   %{name}-libGLESv2 = %{version}-%{release}
Requires:   %{name}-devel = %{version}-%{release}
Provides:   libGLESv2-devel

%description libGLESv2-devel
%{summary}



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
# << install post


%post libEGL -p /sbin/ldconfig

%postun libEGL -p /sbin/ldconfig

%post libGLESv1 -p /sbin/ldconfig

%postun libGLESv1 -p /sbin/ldconfig

%post libGLESv2 -p /sbin/ldconfig

%postun libGLESv2 -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
# << files devel

%files libEGL
%defattr(-,root,root,-)
%{_libdir}/libEGL.so.1
# >> files libEGL
# << files libEGL

%files libEGL-devel
%defattr(-,root,root,-)
%{_includedir}/KHR/*.h
%{_includedir}/EGL/*.h
# >> files libEGL-devel
# << files libEGL-devel

%files libGLESv1
%defattr(-,root,root,-)
%{_libdir}/libGLES_CM.so.1
# >> files libGLESv1
# << files libGLESv1

%files libGLESv1-devel
%defattr(-,root,root,-)
%{_includedir}/GLES/*.h
# >> files libGLESv1-devel
# << files libGLESv1-devel

%files libGLESv2
%defattr(-,root,root,-)
%{_libdir}/libGLESv2.so.2
# >> files libGLESv2
# << files libGLESv2

%files libGLESv2-devel
%defattr(-,root,root,-)
%{_includedir}/GLES2/*.h
# >> files libGLESv2-devel
# << files libGLESv2-devel
